<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Chrome_100648204_Windows.Daisy202Test" errors="0" failures="1" tests="1" time="0.012">
<testcase classname="Chrome_100648204_Windows.Daisy202Test" name="testDaisy202" time="0.012">
<failure type="failed" message="[{&quot;message&quot;:&quot;there are 7 links in content.html expected 7 but was 3&quot;,&quot;name&quot;:&quot;AssertError&quot;,&quot;stack&quot;:&quot;AssertError: there are 7 links in content.html expected 7 but was 3\n    at fail (http://localhost:4224/static/runner.js:356:2295)\n    at assertEquals (http://localhost:4224/static/runner.js:356:4003)\n    at [object Object].&lt;anonymous&gt; (http://localhost:4224/test/test/Daisy202Loader_test.js:160:7)\n    at [object Object].invoke (http://localhost:4224/static/runner.js:403:29)\n    at [object Object].invoke (http://localhost:4224/static/runner.js:544:36)\n    at [object Object].invoke (http://localhost:4224/static/runner.js:473:32)\n    at Object.success (http://localhost:4224/static/runner.js:845:28)\n    at Object.resolveWith (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:975:27)\n    at done (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:6649:14)\n    at XMLHttpRequest.&lt;anonymous&gt; (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:7441:8)&quot;}]">AssertError: there are 7 links in content.html expected 7 but was 3&#13;
&#13;
AssertError: there are 7 links in content.html expected 7 but was 3&#13;
    at [object Object].&lt;anonymous&gt; (http://localhost:4224/test/test/Daisy202Loader_test.js:160:7)&#13;
    at Object.resolveWith (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:975:27)&#13;
    at done (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:6649:14)&#13;
    at XMLHttpRequest.&lt;anonymous&gt; (http://localhost:4224/test/_/js/jQuery/jquery-1.5.2.js:7441:8)&#13;
</failure>
</testcase>
<system-out><![CDATA[[LOG] 1 - xmlToHtml]]></system-out>
</testsuite>
